name: npm-publish
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Get version from package.json
        id: package_version
        run: echo ::set-output name=VERSION::$(jq -r .version package.json)

      - name: Check if the tag exists
        id: tag_check
        run: |
          if git rev-parse v${{ steps.package_version.outputs.VERSION }} >/dev/null 2>&1; then
            echo "Tag for version ${{ steps.package_version.outputs.VERSION }} already exists."
            echo ::set-output name=EXISTS::true
          else
            echo ::set-output name=EXISTS::false
          fi

      - name: Create Git tag
        if: steps.check_tag.outputs.TAG_EXISTS == 'false'
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git tag v${{ steps.get_version.outputs.VERSION }}
          git push origin v${{ steps.get_version.outputs.VERSION }}

      - name: Publish to npm
        if: steps.check_tag.outputs.TAG_EXISTS == 'false'
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_MJRS_PUBLISH }}
